# Generated by Django 5.0.6 on 2024-06-17 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0005_flashcard_delete_flashcards_rename_decks_deck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='deck_id',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='deck_id',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ManyToManyField(to='revise.deck'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
