# Generated by Django 5.0.6 on 2024-07-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0016_history_history_pairing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
