# Generated by Django 5.0.6 on 2024-07-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0018_flashcardconfidence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashcardConfidence',
            new_name='Confidence',
        ),
    ]
