# Generated by Django 5.0.6 on 2024-07-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0029_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friends',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
