# Generated by Django 5.0.6 on 2024-06-16 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0004_decks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Flashcards',
        ),
        migrations.RenameModel(
            old_name='Decks',
            new_name='Deck',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revise.deck'),
        ),
    ]
