# Generated by Django 5.0.6 on 2024-06-17 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0006_remove_deck_deck_id_remove_flashcard_deck_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('deck_name', 'owner'), name='owner decks'),
        ),
    ]
