# Generated by Django 5.0.6 on 2024-06-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0007_deck_owner_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
