# Generated by Django 5.0.6 on 2024-06-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0008_deck_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='public',
            field=models.CharField(default='private', max_length=20),
        ),
    ]
