# Generated by Django 5.0.6 on 2024-07-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0011_remove_flashcard_deck_flashcard_deck'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deck',
            name='owner decks',
        ),
    ]
