# Generated by Django 5.0.6 on 2024-07-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0013_alter_deck_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='share',
            field=models.BooleanField(),
        ),
    ]
