# Generated by Django 5.0.6 on 2024-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0014_alter_deck_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('deck', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
