# Generated by Django 5.0.6 on 2024-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0015_history'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(fields=('user', 'deck'), name='history pairing'),
        ),
    ]
