# Generated by Django 5.0.6 on 2024-07-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0017_rename_datetime_history_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardConfidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('flashcard', models.IntegerField()),
                ('confidence', models.IntegerField()),
            ],
        ),
    ]
