# Generated by Django 5.0.6 on 2024-07-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0019_rename_flashcardconfidence_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
