# Generated by Django 5.0.6 on 2024-07-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0025_flashcard_answer_image_flashcard_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='answer_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
