# Generated by Django 5.0.6 on 2024-07-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0027_alter_flashcard_answer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='rating',
        ),
    ]
