# Generated by Django 5.0.6 on 2024-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0030_friends_friends'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('user_one', 'user_two'), name='friends'),
        ),
    ]
