# Generated by Django 5.0.6 on 2024-07-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0034_remove_confidence_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='confidence',
        ),
        migrations.AddField(
            model_name='confidence',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=3),
            preserve_default=False,
        ),
    ]
